# Generated by Django 3.2.7 on 2021-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
